export const items = [
    {
      name: "Aaradhy Gaur",
      role: "Co-Founder",
      img: "https://randomuser.me/api/portraits/men/10.jpg",
      linkedin: "http://www.linkedin.com/in/aaradhygaur",
    },
    {
      name: "Tanish S.Pareek",
      role: "Co-Founder",
      img: "https://randomuser.me/api/portraits/men/11.jpg",
      linkedin: "http://www.linkedin.com/in/tanish-sunita-pareek",
    },
    {
      name: "Aryan Thacker",
      role: "Tech-Lead",
      img: "https://randomuser.me/api/portraits/men/12.jpg",
      linkedin: "https://www.linkedin.com/in/aryan-thacker/",
    },
    {
      name: "Rashmi Arya",
      role: "Social Media Lead",
      img: "https://randomuser.me/api/portraits/women/13.jpg",
      linkedin: "https://www.linkedin.com/in/rashmee-arya-369bb1285",
    },
    {
      name: "Dimple Pareek",
      role: "Legal Advisor",
      img: "https://randomuser.me/api/portraits/women/14.jpg",
      linkedin: "https://www.linkedin.com/in/dimple-pareek-00773b175/",
    },
    {
      name: "Deependra Singh",
      role: "Content-Lead",
      img: "https://randomuser.me/api/portraits/men/15.jpg",
      linkedin: "https://www.linkedin.com/in/kur-deependra-singh",
    },
    {
      name: "Palak Kumari",
      role: "Marketing Lead",
      img: "https://randomuser.me/api/portraits/women/16.jpg",
      linkedin: "https://www.linkedin.com/in/palak-kumari-b855a521b",
    },
    {
      name: "Nistha Bhura",
      role: "PR Lead",
      img: "https://randomuser.me/api/portraits/women/17.jpg",
      linkedin: "https://www.linkedin.com/in/nistha-bhura-67aa54257",
    },
    {
      name: "Shashank Jangid",
      role: "Design Lead",
      img: "https://randomuser.me/api/portraits/men/18.jpg",
      linkedin: "https://www.linkedin.com/in/shashank-jangid",
    },
    {
      name: "Advay Anand",
      role: "Tech-Team",
      img: "https://randomuser.me/api/portraits/men/19.jpg",
      linkedin: "https://www.linkedin.com/in/advay-anand-a89024277/",
    },
    {
      name: "Divyansh Goel",
      role: "Tech-Team",
      img: "https://randomuser.me/api/portraits/men/20.jpg",
      linkedin: "https://www.linkedin.com/in/divyansh-goel-535522314/",
    },
    {
      name: "Poorva Gupta",
      role: "Tech-Team",
      img: "https://randomuser.me/api/portraits/women/21.jpg",
      linkedin: "https://www.linkedin.com/in/poorva-gupta-934a25222/",
    },
    {
      name: "Vishakha Pathak",
      role: "Social-Media Team",
      img: "https://randomuser.me/api/portraits/women/22.jpg",
      linkedin: "https://www.linkedin.com/in/nikhilbakshi",
    },
    {
      name: "Shubhika Jain",
      role: "Social-Media Team",
      img: "https://randomuser.me/api/portraits/women/23.jpg",
      linkedin: "https://www.linkedin.com/in/deepanshi-sharma",
    },
    {
      name: "Aarna Bhardwaj",
      role: "PR and Content-Team",
      img: "https://randomuser.me/api/portraits/women/24.jpg",
      linkedin: "https://www.linkedin.com/in/meghaverma",
    },
    {
      name: "Satyam Singh",
      role: "Content-Team",
      img: "https://randomuser.me/api/portraits/men/25.jpg",
      linkedin: "http://linkedin.com/in/satyam-singh-108486300",
    },
    {
      name: "Aditi Singh",
      role: "Content-Team",
      img: "https://randomuser.me/api/portraits/women/26.jpg",
      linkedin: "https://www.linkedin.com/in/aditi-singh-13686b24a",
    },
    {
      name: "Ujjwal Singh",
      role: "PR and Marketing Team",
      img: "https://randomuser.me/api/portraits/men/27.jpg",
      linkedin: "https://www.linkedin.com/in/ujjwal-agarwal-67b6a0323",
    },
    {
      name: "Kritika Sharma",
      role: "Design Team",
      img: "https://randomuser.me/api/portraits/women/28.jpg",
      linkedin: "https://www.linkedin.com/in/kritika-sharma-400b1930a",
    },
    {
      name: "Sanskar Chaturvedi",
      role: "Design Team",
      img: "https://randomuser.me/api/portraits/men/29.jpg",
      linkedin: "https://www.linkedin.com/in/sanskar-chaturvedi-4a558024b",
    },
  ];
  